### ISSUE TITLE
Adding a layer for power lines

### ISSUE THREAD

**Issue by mblaine** [watmildon/TIGERMap#24]
I hope this is ok. I wanted to suggest, that since you have layers for pipelines and railways, I also noticed tiger for whatever reason has power lines too.

**Comment by watmildon** [comment]
I am happy to add one myself of merge a PR to do the same. Just need to add a mapstyle layer, add that to setup.js, and add a checkbox in the overlay dropdown in the html.

Probably just power=*?

**Comment by watmildon** [comment]
OSM is having network issues so I'll work on this.

**Comment by mblaine** [comment]
Thanks very cool, thank you! Yeah I can't access the api.

**Comment by watmildon** [comment]
Easy peasy. https://github.com/watmildon/TIGERMap/commit/1f0ccc7af2c630ff5eb92f637fcb479f71094f9b
