### ISSUE TITLE
Adding Puerto Rico

### ISSUE THREAD

**Issue by mblaine** [watmildon/TIGERMap#25]
Also noticed, Puerto Rico has TIGER ways for days but isn't part of the US extract. Would it be a good idea to add it to this map? Thanks!

**Comment by watmildon** [comment]
I was wondering about this the other day! Probably should investigate the other US territories.

**Comment by watmildon** [comment]
I think this is fixed with this https://github.com/watmildon/TIGERMap/commit/d741e122f2c6de119126f96500ffd8a77f809ea8

USVI doesn't seem to have any tiger stuff. Let me know if you discover any other things hanging around. It should get generated later tonight.

**Comment by watmildon** [comment]
The site is updated and looks great. Thanks again for pointing it out!
