### ISSUE TITLE
Add date of the data

### ISSUE THREAD

**Issue by Bauer33333** [watmildon/TIGERMap#35]
It would be nice to have the date (time) the data currently visible on the map is from.
The implementation on the WaterwayMap looks like this: 
![grafik](https://github.com/user-attachments/assets/30375327-10a4-42c0-8068-53818358f4eb)

**Comment by watmildon** [comment]
Thanks for opening this issue. I will try and find some time to get it set up. Definitely a good idea.

**Comment by watmildon** [comment]
I have all the pieces I need for this and it should be rolled out in the next day or two. 

* get the datatime stashed in the pmtiles file during data processing
* query this and jam it into the attribution

WWM stores all this in a sidecar file and I kinda wanted to avoid another thing to lug around but also that mean it got shelved for 5 months. Brains are weird. Thanks for you patience.

**Comment by Bauer33333** [comment]
Thank you for adding it 👍
